version: '3.9'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - UI_URL
      - PORT
      - POSTGRES_HOST=database
      - POSTGRES_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - JWT_TOKEN_SECRET
      - JWT_TOKEN_EXPIRATION_TIME
      - USER_PASSWORD_BCRYPT_SALT_ROUNDS
    ports:
      - 127.0.0.1:${PORT}:${PORT}
    networks:
      - db-network
      - local-network
    volumes:
      - media-volume:/app/media
    depends_on:
      - database

  database:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    # ports:
    #   - 5432:5432
    networks:
      - db-network
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  media-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./media

networks:
  db-network:
    driver: bridge
    internal: true
  local-network:
